# Site settings
baseurl = "http://binlin.nl/"
languageCode = "en-us"
title = "LIN, Bin"
theme = "redlounge"
disqusShortname = "blin"

[params]
	sidebartitle = "LIN, Bin"
	sidebartagline = "A Graduate Student at TU/e"
    sidebarphoto = "/img/photo.png"
	
[[menu.main]]
    name = "Blog"
    url = "/"
	
[[menu.social]]
    pre = "<i class='fa fa-twitter'></i>"
    url = "http://www.twitter.com/wzblin"
    identifier = "twitter"